version: '3'
services:
    db:
      container_name: j-report-db
      build: ./db/
      environment:
        MYSQL_DATABASE: j_report
        MYSQL_ROOT_PASSWORD: gkFnRjKY
      ports:
        - 3306:3306
    app:
      container_name: j-report-app
      build: ./app/
      user: root
      ports:
        - 9000:9000
      links:
        - db
      volumes:
        - ./:/home/j-report
